### PR TITLE
Bump ReactiveCocoa to 4.0.1

### PR DESCRIPTION
**Pull request by Adlai-Holler**
Thanks for maintaining these!

### CODE REVIEW

**Comment by ashfurrow** [comment]
Thanks for the PR! I'll pull this down and push to trunk :+1:

**Comment by ashfurrow** [comment]
Hmm, Result 1.0.2 hasn't been pushed to Trunk yet.

**Comment by Adlai-Holler** [comment]
Thanks for opening an issue at Result. I'll be looking out for it.

**Comment by ashfurrow** [comment]
Coooool, this has been pushed: https://raw.githubusercontent.com/CocoaPods/Specs/bcb45083ded0d224a91ff859c063d0796c58c2b1/Specs/ReactiveCocoa/4.0.1/ReactiveCocoa.podspec.json

**Comment by Adlai-Holler** [comment]
Awesome, this'll improve today's release. Thanks for seeing it through. Love your work!

**Pull request merged**
