### PR TITLE
Updated ReactiveCocoa podspec to 4.2.0

### PR DESCRIPTION
**Pull request by minuscorp**

### CODE REVIEW

**Comment by orta** [comment]
You'll need to change the version too, I expect: https://github.com/mhuusko5/Podspecs/blob/master/ReactiveCocoa.podspec#L3

**Comment by minuscorp** [comment]
This should be it

**Comment by orta** [comment]
Cool, I don't have permission to deploy RAC, so I'll leave that for someone else to merge and release 👍

**Comment by ashfurrow** [comment]
OK, I'm pushing now :+1: @minuscorp if you have a CocoaPods Trunk account, I can add you as an owner of the ReactiveCocoa pod so you can push new versions, just let me know. The basic procedure is, open a PR here, have it reviewed+merged, and then someone pushes to CocoaPods. Let me know if you have any questions!

**Comment by ashfurrow** [comment]
Hmm, got a validation error when I tried to push:

```
➜  Podspecs git:(master) pod trunk push ReactiveCocoa.podspec --allow-warnings
Updating spec repo `master`

CocoaPods 1.0.1 is available.
To update use: `sudo gem install cocoapods`
Until we reach version 1.0 the features of CocoaPods can and will change.
We strongly recommend that you use the latest version at all times.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.0.1

Validating podspec
 -> ReactiveCocoa (4.2.0)
    - WARN  | [ReactiveCocoa/Core,ReactiveCocoa/UI] xcodebuild:  ReactiveCocoa/ReactiveCocoa/Objective-C/RACCompoundDisposable.m:85:12: warning: unused variable 'result' [-Wunused-variable]
    - WARN  | [ReactiveCocoa/Core,ReactiveCocoa/UI] xcodebuild:  ReactiveCocoa/ReactiveCocoa/Objective-C/RACCompoundDisposable.m:132:12: warning: unused variable 'result' [-Wunused-variable]
    - WARN  | [ReactiveCocoa/Core,ReactiveCocoa/UI] xcodebuild:  ReactiveCocoa/ReactiveCocoa/Objective-C/RACSerialDisposable.m:63:12: warning: unused variable 'result' [-Wunused-variable]
    - WARN  | [ReactiveCocoa/Core,ReactiveCocoa/UI] xcodebuild:  ReactiveCocoa/ReactiveCocoa/Objective-C/RACSerialDisposable.m:79:12: warning: unused variable 'result' [-Wunused-variable]
    - ERROR | [ReactiveCocoa/Core,ReactiveCocoa/UI] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [ReactiveCocoa/UI] xcodebuild:  <module-includes>:1:9: note: in file included from <module-includes>:1:
    - NOTE  | [ReactiveCocoa/UI] xcodebuild:  Target Support Files/ReactiveCocoa/ReactiveCocoa-umbrella.h:75:9: note: in file included from Target Support Files/ReactiveCocoa/ReactiveCocoa-umbrella.h:75:
    - ERROR | [ReactiveCocoa/UI] xcodebuild:  ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:67:10: error: 'UIBarButtonItem+RACCommandSupport.h' file not found
    - NOTE  | [ReactiveCocoa/Core,ReactiveCocoa/UI] xcodebuild:  <unknown>:0: error: could not build Objective-C module 'ReactiveCocoa'
    - NOTE  | [ReactiveCocoa/Core] xcodebuild:  <module-includes>:2:9: note: in file included from <module-includes>:2:
    - ERROR | [iOS] [ReactiveCocoa/Core] xcodebuild:  /Users/ash/Library/Developer/Xcode/DerivedData/App-cmyhiklwozkrmrbeteifmqjmebht/Build/Products/Release-iphonesimulator/ReactiveCocoa/ReactiveCocoa.framework/Headers/ReactiveCocoa-Swift.h:100:9: error: 'ReactiveCocoa/ReactiveCocoa.h' file not found
    - ERROR | [OSX] [ReactiveCocoa/Core] xcodebuild:  /Users/ash/Library/Developer/Xcode/DerivedData/App-cmyhiklwozkrmrbeteifmqjmebht/Build/Products/Release/ReactiveCocoa/ReactiveCocoa.framework/Headers/ReactiveCocoa-Swift.h:100:9: error: 'ReactiveCocoa/ReactiveCocoa.h' file not found
    - ERROR | [tvOS] [ReactiveCocoa/Core] xcodebuild:  /Users/ash/Library/Developer/Xcode/DerivedData/App-cmyhiklwozkrmrbeteifmqjmebht/Build/Products/Release-appletvsimulator/ReactiveCocoa/ReactiveCocoa.framework/Headers/ReactiveCocoa-Swift.h:100:9: error: 'ReactiveCocoa/ReactiveCocoa.h' file not found
    - ERROR | [watchOS] [ReactiveCocoa/Core] xcodebuild:  /Users/ash/Library/Developer/Xcode/DerivedData/App-cmyhiklwozkrmrbeteifmqjmebht/Build/Products/Release-watchsimulator/ReactiveCocoa/ReactiveCocoa.framework/Headers/ReactiveCocoa-Swift.h:100:9: error: 'ReactiveCocoa/ReactiveCocoa.h' file not found
```

You can validate a podspec by running `pod spec lint ReactiveCocoa.podspec`. @minuscorp Could you take a look when you get a chance? I don't have any time right now to check it out.

**Comment by minuscorp** [comment]
I've tried many changes without any success in avoiding this errors...

**Comment by ashfurrow** [comment]
It looks like there're two problems: the ReactiveCore/UI project can't find the `UIBarButtonItem+RACCommandSupport.h` file, and the others are probably related to the first, so we should start looking there. Using `--verbose` can help, along with `--no-clean` which leaves behind the project CocoaPods generated. I'll check back in when I can!

**Comment by ashfurrow** [comment]
Sorry I've not had time to look at this, things have been busy 😬

**Comment by minuscorp** [comment]
+1 ... I was unable to either fix it (in the little spare time I had) or investigate more about it... :cry:

**Pull request merged**
